/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GatewayCreateUserData } from '../models';
// @ts-ignore
import type { GatewayCreateUserResponse } from '../models';
// @ts-ignore
import type { MiddlewaresUnauthorized } from '../models';
// @ts-ignore
import type { RequestErrorResponse } from '../models';
/**
 * GatewayApi - axios parameter creator
 * @export
 */
export const GatewayApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a local ocserv user for an authenticated external gateway.
         * @summary Gateway ocserv user creation
         * @param {string} authorization Bearer GATEWAY_API_TOKEN
         * @param {GatewayCreateUserData} request gateway user create data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gatewayUsersPost: async (authorization: string, request: GatewayCreateUserData, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('gatewayUsersPost', 'authorization', authorization)
            // verify required parameter 'request' is not null or undefined
            assertParamExists('gatewayUsersPost', 'request', request)
            const localVarPath = `/gateway/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GatewayApi - functional programming interface
 * @export
 */
export const GatewayApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GatewayApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a local ocserv user for an authenticated external gateway.
         * @summary Gateway ocserv user creation
         * @param {string} authorization Bearer GATEWAY_API_TOKEN
         * @param {GatewayCreateUserData} request gateway user create data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gatewayUsersPost(authorization: string, request: GatewayCreateUserData, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GatewayCreateUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.gatewayUsersPost(authorization, request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GatewayApi.gatewayUsersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GatewayApi - factory interface
 * @export
 */
export const GatewayApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GatewayApiFp(configuration)
    return {
        /**
         * Creates a local ocserv user for an authenticated external gateway.
         * @summary Gateway ocserv user creation
         * @param {GatewayApiGatewayUsersPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gatewayUsersPost(requestParameters: GatewayApiGatewayUsersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<GatewayCreateUserResponse> {
            return localVarFp.gatewayUsersPost(requestParameters.authorization, requestParameters.request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for gatewayUsersPost operation in GatewayApi.
 * @export
 * @interface GatewayApiGatewayUsersPostRequest
 */
export interface GatewayApiGatewayUsersPostRequest {
    /**
     * Bearer GATEWAY_API_TOKEN
     * @type {string}
     * @memberof GatewayApiGatewayUsersPost
     */
    readonly authorization: string

    /**
     * gateway user create data
     * @type {GatewayCreateUserData}
     * @memberof GatewayApiGatewayUsersPost
     */
    readonly request: GatewayCreateUserData
}

/**
 * GatewayApi - object-oriented interface
 * @export
 * @class GatewayApi
 * @extends {BaseAPI}
 */
export class GatewayApi extends BaseAPI {
    /**
     * Creates a local ocserv user for an authenticated external gateway.
     * @summary Gateway ocserv user creation
     * @param {GatewayApiGatewayUsersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GatewayApi
     */
    public gatewayUsersPost(requestParameters: GatewayApiGatewayUsersPostRequest, options?: RawAxiosRequestConfig) {
        return GatewayApiFp(this.configuration).gatewayUsersPost(requestParameters.authorization, requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }
}

