/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GatewayDeleteUserResponse
 */
export interface GatewayDeleteUserResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GatewayDeleteUserResponse
     */
    'deleted'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GatewayDeleteUserResponse
     */
    'remote_user_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayDeleteUserResponse
     */
    'username'?: string;
}

