/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GatewayUpdateUserSubscriptionData
 */
export interface GatewayUpdateUserSubscriptionData {
    /**
     * 
     * @type {boolean}
     * @memberof GatewayUpdateUserSubscriptionData
     */
    'activate'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GatewayUpdateUserSubscriptionData
     */
    'expire_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayUpdateUserSubscriptionData
     */
    'group'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GatewayUpdateUserSubscriptionData
     */
    'reset_traffic_usage'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GatewayUpdateUserSubscriptionData
     */
    'traffic_limit_bytes'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUpdateUserSubscriptionData
     */
    'traffic_limit_gb'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GatewayUpdateUserSubscriptionData
     */
    'unlimited'?: boolean;
}

