/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GatewayCreateUserData
 */
export interface GatewayCreateUserData {
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserData
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserData
     */
    'expire_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserData
     */
    'group': string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserData
     */
    'password': string;
    /**
     * 
     * @type {number}
     * @memberof GatewayCreateUserData
     */
    'traffic_limit_gb'?: number;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserData
     */
    'traffic_type': GatewayCreateUserDataTrafficTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof GatewayCreateUserData
     */
    'unlimited'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserData
     */
    'username': string;
}

export const GatewayCreateUserDataTrafficTypeEnum = {
    FREE: 'Free',
    MONTHLY_TRANSMIT: 'MonthlyTransmit',
    MONTHLY_RECEIVE: 'MonthlyReceive',
    MONTHLY_RX_TX: 'MonthlyRxTx',
    TOTALLY_TRANSMIT: 'TotallyTransmit',
    TOTALLY_RECEIVE: 'TotallyReceive',
    TOTALLY_RX_TX: 'TotallyRxTx'
} as const;

export type GatewayCreateUserDataTrafficTypeEnum = typeof GatewayCreateUserDataTrafficTypeEnum[keyof typeof GatewayCreateUserDataTrafficTypeEnum];


