/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GatewayUserStatusResponse
 */
export interface GatewayUserStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GatewayUserStatusResponse
     */
    'active'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GatewayUserStatusResponse
     */
    'deactivated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserStatusResponse
     */
    'deactivated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserStatusResponse
     */
    'expire_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserStatusResponse
     */
    'group'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GatewayUserStatusResponse
     */
    'locked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserStatusResponse
     */
    'remote_user_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'rx_bytes'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'rx_gb'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'traffic_consumed_bytes'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'traffic_consumed_gb'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'traffic_limit_bytes'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'traffic_limit_gb'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'traffic_remaining_bytes'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'traffic_remaining_gb'?: number;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserStatusResponse
     */
    'traffic_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'tx_bytes'?: number;
    /**
     * 
     * @type {number}
     * @memberof GatewayUserStatusResponse
     */
    'tx_gb'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GatewayUserStatusResponse
     */
    'unlimited'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GatewayUserStatusResponse
     */
    'username'?: string;
}

