/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GatewayCiscoSetupResponse
 */
export interface GatewayCiscoSetupResponse {
    /**
     * 
     * @type {string}
     * @memberof GatewayCiscoSetupResponse
     */
    'certificate_import_uri'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCiscoSetupResponse
     */
    'certificate_password'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCiscoSetupResponse
     */
    'connection_create_uri'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCiscoSetupResponse
     */
    'connection_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCiscoSetupResponse
     */
    'expires_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCiscoSetupResponse
     */
    'server_address'?: string;
    /**
     * 
     * @type {number}
     * @memberof GatewayCiscoSetupResponse
     */
    'server_port'?: number;
}

