/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GatewayCreateUserResponse
 */
export interface GatewayCreateUserResponse {
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserResponse
     */
    'expire_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserResponse
     */
    'group'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserResponse
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserResponse
     */
    'remote_user_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof GatewayCreateUserResponse
     */
    'traffic_limit_gb'?: number;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserResponse
     */
    'traffic_type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GatewayCreateUserResponse
     */
    'unlimited'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GatewayCreateUserResponse
     */
    'username'?: string;
}

